lab4-6/lab4/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url

from .blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.MainView.as_view(), name='main'),
    url(r'^(?P<pk>[0-9]+)/$', views.PostView.as_view(), name='postDetail'),
    url(r'^registration/', views.RegistrationForm.as_view(), name='registration'),
    url(r'^login/', views.LoginForm.as_view(), name='login'),
    url(r'^profile/', views.user_profile, name='profile'),
    url(r'^logout/', views.LogoutForm.as_view(), name='logout'),
]

lab4-6/lab4/blog/models.py
from django.db import models

import pymysql


class Post(models.Model):
    post_head = models.CharField(max_length=70)
    post_text = models.CharField(max_length=255)
    publication_date = models.DateField('Date published')

    def __str__(self):
        return self.post_head


class Comment(models.Model):
    id_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=70)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return self.answer_text


class Connection:
    def __init__(self, user, password, db, host='localhost'):
        self.user = user
        self.host = host
        self.password = password
        self.db = db
        self._connection = None

    @property
    def connection(self):
        return self._connection

    def __enter__(self):
        self.connect()

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.disconnect()

    def connect(self):
        if not self._connection:
            self._connection = pymysql.connect(
                host=self.host,
                user=self.user,
                passwd=self.password,
                db=self.db
            )

    def disconnect(self):
        if self._connection:
            self._connection.close()


class Userr:

    def __init__(self, db_connection, name, age, email):
        self.db_connection = db_connection.connection,
        self.name = name,
        self.age = age,
        self.email = email

    def save(self):
        c = self.db_connection.cursor()
        c.execute("INSERT INTO users (name, age, email) VALUES (%s, %s, %s)",
        ('Рати', '11', '41@mail.ru'))
        self.db_connection.commit()
        c.close()


class UserModel(models.Model):
    name = models.CharField(max_length=30)
    age = models.IntegerField(default=0)
    email = models.CharField(max_length=30)

lab4-6/lab4/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=10, label='Почта')
    first_name = forms.CharField(max_length=30, label='Имя')
    last_name = forms.CharField(max_length=30, label='Фамилия')

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = ''
        self.fields['password1'].help_text = ''

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'email')


class LoginForm(AuthenticationForm):
    pass

lab4-6/lab4/blog/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.db.models import Count
from django.views import generic
from django.views.generic import FormView, View
from lab4.blog.forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
import datetime
from .models import *


class MainView(generic.ListView):
    template_name = 'main.html'
    context_object_name = 'main_postList'

    def get_queryset(self):
        return Post.objects.annotate(num=Count('comment')).order_by('-publication_date')[:5]


class PostView(generic.DeleteView):
    model = Post
    template_name = 'post.html'


class RegistrationForm(FormView):
    form_class = RegistrationForm
    success_url = "/login/"
    template_name = "registration.html"

    def form_valid(self, form):
        form.save()
        return super(RegistrationForm, self).form_valid(form)

    def form_invalid(self, form):
        return super(RegistrationForm, self).form_invalid(form)


class LoginForm(FormView):
    form_class = LoginForm
    success_url = "/profile/"
    template_name = "login.html"

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginForm, self).form_valid(form)


@login_required(login_url='/login/')
def user_profile(request):
    return render(request, 'profile.html')


class LogoutForm(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect("/")

lab4-6/templates/comment.html
{%  load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
<script src="{% static 'js/ajax.js' %}"></script>

<li class="mb-3">
    <div class="col-4 h-25 p-0 text-muted">
        <span id="{{ comment.id }}">{{ comment.rating }}</span>
        <span class="commentRating m-0 ml-1 ajax" onclick="loadRating({{ comment.id }})"><i class="fas fa-caret-up"></i></span>
        <span class="commentRating m-0 ajax" onclick="loadRating({{ comment.id }})"><i class="fas fa-caret-down"></i></span>
    </div>
    {{ comment.answer_text }}
</li>

lab4-6/templates/login.html
<form method="POST">
   {% csrf_token %}
   {{ form.as_p }}
   <button type="submit">+</button>
</form>

lab4-6/templates/main.html

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
<!-- Add icon library -->
<script src="https://kit.fontawesome.com/7e4289d0d7.js" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- Navigation bar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-2">
    <div class="w-auto">
        <button class="navbar-toggler mr-2" type="button" data-toggle="collapse" data-target="#navContent">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand mr-auto" href="#">SOMETHING</a>
    </div>

    <div class="navbar-collapse collapse w-auto" id="navContent">
        <ul class="navbar-nav mx-auto">
            <a class="nav-link" href="/">MAIN</a>
            <a class="nav-link" href="#">NEWS</a>
            <a class="nav-link" href="#">SEARCH</a>
        </ul>
    </div>

    <div class="navbar-nav w-auto justify-content-end">
        <a class="nav-link navbar-nav" href="#">JOIN<i class="ml-2 my-1 fas fa-sign-in-alt"></i> </a>
    </div>
</nav>


<div class="justify-content-center w-50 mx-auto">

            <div class="card m-2 mb-4 mt-4">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="/{{ post.id }}/"></a>
                    </h5>
                    <p class="card-text"></p>
                </div>
                <div class="card-footer">
                    <span><i class="fas fa-comments"></i> </span>
                </div>
            </div>
        </div>

</div>

lab4-6/templates/post.html
{% extends 'main.html' %}

{% block body %}
    <div class="card">
      <div class="card-body">
          <h5 class="card-title"> {{ post.post_head }} </h5>
          <p class="card-text">{{post.post_text}}</p>
      </div>
    </div>

    <div class="card mt-4">
      <div class="card-body">
          <ul class="list-unstyled">
              {% for comment in post.comment_set.all %}
                  {% include 'comment.html' with comment=comment %}
              {% empty %}
                  <div class="alert alert-info" role="alert">
                        Комментариев к этой записи пока нет.
                  </div>
              {% endfor %}
          </ul>

      </div>
    </div>

{% endblock %}

lab4-6/templates/profile.html
<b>JOINED</b><br>
<a href="/logout">EXIT</a>

lab4-6/templates/registration.html
<form method="POST">
   {% csrf_token %}
   {{ form.as_p }}
   <button type="submit">+</button>
</form>